version: '3'

services:
  backend:
    build:
      context: ./guestlist_backend
      dockerfile: Dockerfile.dev
      args:
        NODE_ENV: development
    image: be-my-guest:dev
    volumes:
      - ./guestlist_backend:/home/node/app
      - /home/node/app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"